In [18]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tensor_one_d = tf.constant([2,0,-3,8,90.], dtype = tf.float32)
print(tensor_one_d)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [10]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [13]:
tensor_three_d = tf.constant([
    [[1,2,0],[2,5,-1]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
    [[2,1,9],[4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [17]:
tensor_four_d = tf.constant([
    [
        [[8,2,5],[2,3,3]],
        [[3,2,4],[5,8,3]],
        [[0,2,5],[0,4,3]],
        [[4,5,3],[3,1,1]]
    ],
    [
        [[2,1,9],[4,-3,32]],
        [[5,8,0],[2,7,0]],
        [[10,2,0],[1,0,2]],
        [[1,2,0],[3,5,-1]]
    ],
    [
        [[3,8,7],[2,3,2]],
        [[0,5,1],[1,7,0]],
        [[0,2,0],[1,10,0]],
        [[0,2,5],[5,3,1]]
    ],
])
print(tensor_four_d.shape)
print(tensor_four_d.ndim)

(3, 4, 2, 3)
4


In [19]:
#casting tf.constant > 0 becomes false otherwise becomes true

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_one_d)


tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [20]:
import numpy as np

np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [21]:
# convert numpy to tensor
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [24]:
#identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [30]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,2],
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]], shape=(2, 2, 3, 3), dtype=bool)


In [33]:
fill_tensor = tf.fill([3, 3], 9, name = None)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [34]:
ones_tensor = tf.ones(
    shape = [2,2], 
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [37]:
ones_like_tensor = tf.ones_like(
    tensor_two_d
)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(4, 3), dtype=int32)


In [39]:
zeros_like_tensor = tf.zeros_like(
    tensor_two_d
)
print(zeros_like_tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]], shape=(4, 3), dtype=int32)


In [53]:
random_tensor = tf.random.normal(
    shape =[3,3],
    mean=100.0,
    stddev=10.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 93.91867  113.30861   97.43258 ]
 [ 92.62877  100.942764 108.51121 ]
 [102.15723   98.34765   97.139244]], shape=(3, 3), dtype=float32)
