In [2]:
import tensorflow as tf

In [11]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:2]) #slice out
print(tensor_indexed[:4])
print(tensor_indexed[3:])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[0:3,:])
print(tensor_two_d[0:3,:2])
print(tensor_two_d[0:2,1:3])
print(tensor_two_d[:,1])
print(tensor_two_d[...,1])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  0]
 [ 5 -1]], shape=(2, 2), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
