In [1]:
import tensorflow as tf

In [4]:
x_abs = tf.constant([-2.25,3.25])
print(tf.abs(x_abs))
print(tf.abs(tf.constant(-0.2)))

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)
tf.Tensor(0.2, shape=(), dtype=float32)


In [6]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [7]:
tf.sqrt((-2.25)**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [11]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7,8,3,0,11,2], dtype = tf.int32)

print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2)) #makes infinity
print(tf.math.divide_no_nan(x_1,x_2)) #return 0 if devided by 0


tf.Tensor([12 11  9  6 15  8], shape=(6,), dtype=int32)
tf.Tensor([-2 -5  3  6 -7  4], shape=(6,), dtype=int32)
tf.Tensor([35 24 18  0 44 12], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.375      2.                inf 0.36363636 3.        ], shape=(6,), dtype=float64)
tf.Tensor([0.71428571 0.375      2.         0.         0.36363636 3.        ], shape=(6,), dtype=float64)


In [14]:
#broadcasting
x_1 = tf.constant([[5,3,6,6,4,6],[1,2,3,4,5,6]], dtype = tf.int32)
x_2 = tf.constant([7], dtype = tf.int32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype = tf.int32)

print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_stretched))

tf.Tensor(
[[12 10 13 13 11 13]
 [ 8  9 10 11 12 13]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[12 10 13 13 11 13]
 [ 8  9 10 11 12 13]], shape=(2, 6), dtype=int32)


In [15]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([[5],[1],[3]], dtype = tf.int32)

print(tf.multiply(x_1,x_2))

tf.Tensor(
[[25 15 30 30 20 30]
 [ 5  3  6  6  4  6]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [20]:
x_1 = tf.constant([5,3,6,6,4,60], dtype = tf.int32)
x_2 = tf.constant([7,8,3,0,11,2], dtype = tf.int32)
print(tf.math.minimum(x_1,x_2))
print(tf.math.maximum(x_1,x_2))
print(tf.math.argmax(x_1)) # index of maximum value
print(tf.math.argmin(x_2)) # index of maximum value

tf.Tensor([5 3 3 0 4 2], shape=(6,), dtype=int32)
tf.Tensor([ 7  8  6  6 11 60], shape=(6,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [21]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.argmax(tensor_two_d,0)) # max value of each colunm in 2x2 matrix

tf.Tensor([1 1 3], shape=(3,), dtype=int64)


In [22]:
x_1 = tf.constant([5,3,6,6,4,60], dtype = tf.int32)
x_2 = tf.constant([7,3,3,6,11,30], dtype = tf.int32)
print(tf.math.equal(x_1,x_2))

tf.Tensor([False  True False  True False False], shape=(6,), dtype=bool)


In [26]:
x_1 = tf.constant([[5,3,6,6,4,6],[3,2,1,2,6,7]])
x_2 = tf.constant([[7,8,3,0,11,2],[3,2,6,2,3,7]])

print(tf.pow(x_1,x_2))
print(tf.pow(3,4))
print(tf.pow(tf.constant(3),tf.constant(4)))

tf.Tensor(
[[  78125    6561     216       1 4194304      36]
 [     27       4       1       4     216  823543]], shape=(2, 6), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)


In [37]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
], dtype = tf.float32)

# Summing up all elements on matrix
print(tf.math.reduce_sum(
    tensor_two_d, axis=None, keepdims=False, name=None
)) 

# Summing up colunm elements into 1d tensor
print(tf.math.reduce_sum(
    tensor_two_d, axis=0, keepdims=False, name=None
)) 

# Reducing to the minimum value of the elements
print(tf.math.reduce_min(
    tensor_two_d, axis=None, keepdims=False, name=None
))

print(tf.math.reduce_mean(
    tensor_two_d, axis=0, keepdims=False, name=None
))

print(tf.math.reduce_std(
    tensor_two_d, axis=0, keepdims=True, name=None
))


tf.Tensor(35.0, shape=(), dtype=float32)
tf.Tensor([ 7. 15. 13.], shape=(3,), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32)
tf.Tensor([1.75 3.75 3.25], shape=(3,), dtype=float32)
tf.Tensor([[0.8291562 1.299038  3.8324275]], shape=(1, 3), dtype=float32)


In [38]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

In [42]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [7,3,1]
], dtype = tf.float32)

print(tf.math.top_k(tensor_two_d, k = 1))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.],
       [5.],
       [6.],
       [7.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [0]])>)
