In [1]:
import tensorflow as tf

In [10]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

c = tf.matmul(a, b)
print(c)
print(a@b)


a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[2, 3])
d = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(d)


tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)


In [16]:
print(a)
print(tf.transpose(a))
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [18]:
a = tf.constant([
    [[1,2],[2,5,]],
    [[10,2],[1,0]],
    [[5,8],[2,7]],
    [[2,1],[4,-3]]
])

b = tf.constant([
    [[3,2,-7],[2,10,-1]],
    [[1,2,4],[1,20,3]],
    [[0,80,20],[2,7,0]],
    [[2,11,19],[14,-33,32]]
])

print(a.shape)
print(b.shape)

print(a@b)


(4, 2, 2)
(4, 2, 3)
tf.Tensor(
[[[  7  22  -9]
  [ 16  54 -19]]

 [[ 12  60  46]
  [  1   2   4]]

 [[ 16 456 100]
  [ 14 209  40]]

 [[ 18 -11  70]
  [-34 143 -20]]], shape=(4, 2, 3), dtype=int32)


In [26]:
a = tf.ones([5,5])
print(tf.linalg.band_part(a, 0, -1))
print(tf.linalg.band_part(a, -1, 0))
print(tf.linalg.band_part(a, 1, -1))
print(tf.linalg.band_part(a, 0, 3))

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [30]:
a = tf.constant(
    [[3,2,-7],[2,10,-1],[1,-4,1]], dtype=tf.float32
)
print(tf.linalg.inv(a))

tf.Tensor(
[[ 0.04347825  0.18840575  0.4927536 ]
 [-0.02173913  0.07246377 -0.07971014]
 [-0.13043478  0.10144926  0.18840578]], shape=(3, 3), dtype=float32)


In [31]:
a = tf.constant(
    [[3,2,-7],[2,10,-1],[1,-4,1]], dtype=tf.float32
)
print(tf.linalg.trace(a))
#sum of diagonal elements

tf.Tensor(14.0, shape=(), dtype=float32)


In [38]:
import numpy as np

a = tf.constant([
    [[1,2],[2,5,]],
    [[10,2],[1,0]]
])

b = tf.constant([
    [[3,2,-7],[2,10,-1]],
    [[1,2,4],[1,20,3]]
])

print(np.einsum('bij,bjk -> bik',a,b))
print(np.einsum('bij -> bi',a))

c = np.array([[1,2],[3,4]])
print(np.einsum('ij -> i',c))


[[[  7  22  -9]
  [ 16  54 -19]]

 [[ 12  60  46]
  [  1   2   4]]]
[[ 3  7]
 [12  1]]
[3 7]


In [40]:
# Q = batchsize, s_q, modelsize
# K = batchsize, s_k, modelsize

Q = np.random.randn(32,64,512) #bqm
K = np.random.randn(32,128,512) #bkm

np.einsum('bqm,bkm->bqk', Q, K).shape

(32, 64, 128)

In [42]:
A = np.random.randn(2,4,4,2) #bcij
B = np.random.randn(2,4,4,1) #bcik

np.einsum("bcik,bcij -> bc", A, B).shape

(2, 4)