In [2]:
import tensorflow as tf

tensor_three_d = tf.constant([
    [[1,2,0],[2,5,-1]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
    [[2,1,9],[4,-3,32]]
])
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 0).shape)


(4, 2, 3)
(1, 4, 2, 3)


In [11]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
print(tf.expand_dims(x, axis = 0))
print(tf.expand_dims(x, axis = 3))
for i in range(2):
    x = tf.squeeze(x, axis = 0)
print(x)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)
tf.Tensor(
[[[[2]
   [3]
   [4]
   [5]]]], shape=(1, 1, 4, 1), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [14]:
tensor_three_d = tf.constant([
    [[1,2,0],[2,5,-1]]
])

print(tensor_three_d.shape)
print(tf.squeeze(tensor_three_d, axis = 0)) # 1 expected to be squeezed

(1, 2, 3)
tf.Tensor(
[[ 1  2  0]
 [ 2  5 -1]], shape=(2, 3), dtype=int32)


In [19]:
tensor_three_d = tf.constant([
    [[1,2,0],[2,5,-1]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
    [[2,1,9],[4,-3,32]]
])

print(tensor_three_d.shape)
print(tf.reshape(tensor_three_d,[4,1,6]).shape)
print(tf.reshape(tensor_three_d,[4,3,2]).shape)
print(tf.reshape(tensor_three_d,[8,1,3]).shape)

(4, 2, 3)
(4, 1, 6)
(4, 3, 2)
(8, 1, 3)


In [6]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)
print(tf.concat([t1, t2], axis = 0))
print(tf.concat([t1, t2], axis = 1))

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [16]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)
tf.stack([t1, t2],axis=0)

(2, 3)
(2, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])>

In [25]:
t = tf.constant([[2, 3, 4], [6, 7, 8]])
paddings = tf.constant([[1, 1,], [1, 1]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))  # [[0, 0, 0, 0, 0, 0, 0],
                                        #  [0, 0, 1, 2, 3, 0, 0],
                                        #  [0, 0, 4, 5, 6, 0, 0],
                                        #  [0, 0, 0, 0, 0, 0, 0]]

print(tf.pad(t, paddings, "REFLECT"))   # [[6, 5, 4, 5, 6, 5, 4],
                                        #  [3, 2, 1, 2, 3, 2, 1],
                                        #  [6, 5, 4, 5, 6, 5, 4],
                                        #  [3, 2, 1, 2, 3, 2, 1]]

print(tf.pad(t, paddings, "SYMMETRIC")) # [[2, 1, 1, 2, 3, 3, 2],
                                        #  [2, 1, 1, 2, 3, 3, 2],
                                        #  [5, 4, 4, 5, 6, 6, 5],
                                        #  [5, 4, 4, 5, 6, 6, 5]]

tf.Tensor(
[[0 0 0 0 0]
 [0 2 3 4 0]
 [0 6 7 8 0]
 [0 0 0 0 0]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[7 6 7 8 7]
 [3 2 3 4 3]
 [7 6 7 8 7]
 [3 2 3 4 3]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[2 2 3 4 4]
 [2 2 3 4 4]
 [6 6 7 8 8]
 [6 6 7 8 8]], shape=(4, 5), dtype=int32)


In [27]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[3].numpy()

tf.gather(
    params, [1,2,3], validate_indices=None, axis=None, batch_dims=0, name=None
)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [29]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(tf.gather(params, indices=[3,1]).numpy())


print(tf.gather(params, indices=[2,1], axis=1).numpy())


[[30. 31. 32.]
 [10. 11. 12.]]
[[ 2.  1.]
 [12. 11.]
 [22. 21.]
 [32. 31.]]


In [30]:
tf.gather_nd(
    indices = [[1],
               [0]],
    params = [['a', 'b', 'c'],
              ['d', 'e', 'f']]).numpy()



array([[b'd', b'e', b'f'],
       [b'a', b'b', b'c']], dtype=object)

In [31]:
tf.gather_nd(
    indices = [[0, 1], [1, 0]],
    params = [[['a0', 'b0'], ['c0', 'd0']],
              [['a1', 'b1'], ['c1', 'd1']]]).numpy()

array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)