In [1]:
import tensorflow as tf
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [6]:
tensor_two_d = ([ # tensor is supposed to be rectangular
    [1,2,0],
    [3,],
    [1,5,6,5,6],
    [2,3]
])
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [8]:
T, F = (True, False)

tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()


[[1, 3], [], [7]]

In [9]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [10]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [11]:
print(tf.RaggedTensor.from_row_starts(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_starts=[0, 4, 4, 7, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [12]:
dt = tf.constant([[5, 7, 0], [0, 3, 0], [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)
tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])


<tf.RaggedTensor [[5], [], [6, 0, 0]]>